// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroupOne.Models
{
    public partial class OrdersProduct
    {
        public int OrderProductId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public int OrdProQty { get; set; }
        public decimal OrdProPrice { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Product Product { get; set; }
    }
}