// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GroupOne.Models
{
    public partial class OrdersPayment
    {
        public int OrderPaymentId { get; set; }
        public int OrderId { get; set; }
        public int ReferenceNum { get; set; }

        public virtual Orders Order { get; set; }
        public virtual Payment ReferenceNumNavigation { get; set; }
    }
}